import Head from 'next/head'
import Restaurants from '../components/RestaurantList/index'

export default function Home(props) {
  return (
    <div>
      {console.log('home props', props.query)}
      <Head>
        <title>Food Online Order App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      < Restaurants query={props.query} />
    </div>
  )
}
