import Head from 'next/head'
import { gql } from "@apollo/client";

import client from "../lib/apollo-client";
import Restaurants from '../components/restaurants';

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
    {
      restaurants {
          id
          name 
          description 
          image {url} 
      }
    }
    `,
  });

  //console.log('restaurants', data.restaurants);

  return {
    props: {
      restaurants: data.restaurants,
    },
  };
}

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Food Online Order App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Restaurants restaurants={props.restaurants} />
    </div>
  )
}